import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';

import { copyFileSync, existsSync, mkdirSync } from 'fs';
import path from 'path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Obsidian Antigravity Plugin
*/
`;

const prod = process.argv[2] === 'production';

const VAULT_PLUGIN_DIR = process.env.OBSIDIAN_PLUGIN_PATH || 
  path.join(process.env.HOME || '/home/kyc', 'Obsidians/Omarchy-Desktop/.obsidian/plugins/antigravity');

const copyToVaultPlugin = {
  name: 'copy-to-vault',
  setup(build) {
    build.onEnd((result) => {
      if (result.errors.length > 0) return;
      if (!existsSync(VAULT_PLUGIN_DIR)) {
        mkdirSync(VAULT_PLUGIN_DIR, { recursive: true });
      }
      for (const file of ['main.js', 'manifest.json', 'styles.css']) {
        if (existsSync(file)) {
          copyFileSync(file, path.join(VAULT_PLUGIN_DIR, file));
        }
      }
      console.log(`Synced plugin files to ${VAULT_PLUGIN_DIR}`);
    });
  },
};

const context = await esbuild.context({
  plugins: [copyToVaultPlugin],
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtinModules,
    ...builtinModules.map(m => `node:${m}`),
  ],
  format: 'cjs',
  target: 'es2022',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
